steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.score', '-t', 'us-central1-docker.pkg.dev/otimizador-cargas/cloud-run-source-deploy/ecommerceflow-vertex-scoring:latest', '.']
images:
- 'us-central1-docker.pkg.dev/otimizador-cargas/cloud-run-source-deploy/ecommerceflow-vertex-scoring:latest'
