FROM python:3.12-slim

WORKDIR /app

COPY requirements_vertex.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements_vertex.txt

COPY vertex_predictor_app.py .

ENV AIP_HTTP_PORT=8080

CMD exec uvicorn vertex_predictor_app:app --host 0.0.0.0 --port ${AIP_HTTP_PORT}
